import SyGMA_reaction_rules as React
import pandas as pd
from rdkit import Chem

'''Note:
Every time you add something here you have to add the functions in file.py alerts_index, calculator and alerts
'''

def descriptor(mol: Chem.rdchem.Mol):
    REACTION_N_dealkylation_1=[];REACTION_N_dealkylation_2=[];REACTION_N_dealkylation_3=[];REACTION_N_dealkylation_4=[];REACTION_N_dealkylation_5=[];REACTION_N_dealkylation_6=[];REACTION_N_dealkylation_7=[];REACTION_N_dealkylation_8=[];REACTION_N_dealkylation_9=[];REACTION_N_dealkylation_10=[];REACTION_N_dealkylation_11=[];REACTION_N_dealkylation_12=[];REACTION_N_dealkylation_13=[];REACTION_N_dealkylation_14=[];REACTION_N_dealkylation_15=[];REACTION_N_dealkylation_16=[];REACTION_N_dealkylation_17=[];REACTION_N_dealkylation_18=[];REACTION_N_dealkylation_19=[];REACTION_N_dealkylation_20=[];REACTION_N_dealkylation_21=[];REACTION_O_demethylation_1=[];REACTION_O_demethylation_2=[];REACTION_O_demethylation_3=[];REACTION_O_demethylation_4=[];REACTION_O_demethylation_5=[];REACTION_O_demethylation_6=[];REACTION_O_demethylation_7=[];REACTION_O_demethylation_8=[];REACTION_S_dealkylation_1=[];REACTION_ aromatic hydroxylation_1=[];REACTION_ aromatic hydroxylation_2=[];REACTION_ aromatic hydroxylation_3=[];REACTION_ aromatic hydroxylation_4=[];REACTION_ aromatic hydroxylation_5=[];REACTION_ aromatic hydroxylation_6=[];REACTION_ aromatic hydroxylation_7=[];REACTION_ aromatic hydroxylation_8=[];REACTION_ aromatic hydroxylation_9=[];REACTION_ aromatic hydroxylation_10=[];REACTION_ aromatic hydroxylation_11=[];REACTION_carboxylation_1=[];REACTION_carboxylation_2=[];REACTION_carboxylation_3=[];REACTION_carboxylation_4=[];REACTION_carboxylation_5=[];REACTION_aliphatic_hydroxylation_1=[];REACTION_aliphatic_hydroxylation_2=[];REACTION_aliphatic_hydroxylation_3=[];REACTION_aliphatic_hydroxylation_4=[];REACTION_aliphatic_hydroxylation_5=[];REACTION_aliphatic_hydroxylation_6=[];REACTION_aliphatic_hydroxylation_7=[];REACTION_aliphatic_hydroxylation_8=[];REACTION_aliphatic_hydroxylation_9=[];REACTION_aliphatic_hydroxylation_10=[];REACTION_aliphatic_hydroxylation_11=[];REACTION_aliphatic_hydroxylation_12=[];REACTION_aliphatic_hydroxylation_13=[];REACTION_aliphatic_hydroxylation_14=[];REACTION_benzylic_hydroxylation_1=[];REACTION_benzylic_hydroxylation_2=[];REACTION_benzylic_hydroxylation_3=[];REACTION_benzylic_hydroxylation_4=[];REACTION_benzylic_hydroxylation_5=[];REACTION_benzylic_hydroxylation_6=[];REACTION_reduction_1=[];REACTION_reduction_2=[];REACTION_reduction_3=[];REACTION_reduction_4=[];REACTION_reduction_5=[];REACTION_reduction_6=[];REACTION_reduction_7=[];REACTION_reduction_8=[];REACTION_reduction_9=[];REACTION_aldehyde_oxidation_1=[];REACTION_aldehyde_oxidation_2=[];REACTION_O_deacetylation_1=[];REACTION_N_deacetylation_1=[];REACTION_decarboxylation_1=[];REACTION_decarboxylation_2=[];REACTION_decarboxylation_3=[];REACTION_dehydrogenation_1=[];REACTION_dehydrogenation_2=[];REACTION_dehydrogenation_3=[];REACTION_dehydrogenation_4=[];REACTION_dehydrogenation_5=[];REACTION_dehydrogenation_6=[];REACTION_dehydrogenation_7=[];REACTION_dehydration_1=[];REACTION_dehydration_2=[];REACTION_dehydration_3=[];REACTION_primary_alcohol_oxidatyion_to_carboxyl_1=[];REACTION_primary_alcohol_oxidatyion_to_carboxyl_2=[];REACTION_secondary_alcohol_oxidation_to_carbonyl_1=[];REACTION_secondary_alcohol_oxidation_to_carbonyl_2=[];REACTION_S_oxidation_1=[];REACTION_S_oxidation_2=[];REACTION_S_oxidation_3=[];REACTION_S_oxidation_4=[];REACTION_S_oxidation_5=[];REACTION_S_oxidation_6=[];REACTION_S_oxidation_7=[];REACTION_S_oxidation_8=[];REACTION_S_oxidation_9=[];REACTION_epoxide_hydrolysis_1=[];REACTION_epoxide_hydrolysis_2=[];REACTION_oxidative_deamination_1=[];REACTION_oxidative_deamination_2=[];REACTION_oxidative_deamination_3=[];REACTION_oxidative_deamination_4=[];REACTION_nitro_1=[];REACTION_nitro_2=[];REACTION_nitro_3=[];REACTION_dehalogenation_1=[];REACTION_dehalogenation_2=[];REACTION_dehalogenation_3=[];REACTION_dehalogenation_4=[];REACTION_condensation_1a=[];REACTION_condensation_1b=[];REACTION_condensation_1c=[];REACTION_condensation_2a=[];REACTION_condensation_2b=[];REACTION_condensation_2c=[];REACTION_condensation_3a=[];REACTION_condensation_3b=[];REACTION_condensation_3c=[];REACTION_condensation_3d=[];REACTION_condensation_5a=[];REACTION_condensation_5b=[];REACTION_condensation_5c=[];REACTION_condensation_5d=[];REACTION_condensation_6a=[];REACTION_condensation_6b=[];REACTION_condensation_6c=[];REACTION_condensation_6d=[];REACTION_hydrolysis_1=[];REACTION_hydrolysis_2=[];REACTION_hydrolysis_3=[];REACTION_hydrolysis_4=[];REACTION_hydrolysis_5=[];REACTION_hydrolysis_6=[];REACTION_hydrolysis_7=[];REACTION_hydrolysis_8=[];REACTION_hydrolysis_9=[];REACTION_hydrolysis_10=[];REACTION_N_oxidation_1=[];REACTION_N_oxidation_2=[];REACTION_N_oxidation_3=[];REACTION_N_oxidation_4=[];REACTION_N_oxidation_5=[];REACTION_acetyl_shift_1=[];REACTION_tautomerisation_1=[];REACTION_special_rules_1=[];REACTION_special_rules_2=[];REACTION_special_rules_3=[];REACTION_special_rules_4=[];REACTION_special_rules_5=[];REACTION_special_rules_6=[];REACTION_special_rules_7=[];REACTION_special_rules_8=[];REACTION_special_rules_9=[];REACTION_special_rules_10=[];REACTION_special_rules_11=[];REACTION_special_rules_12=[];REACTION_special_rules_13=[];REACTION_special_rules_14=[];REACTION_special_rules_15=[];REACTION_steroids_1=[];REACTION_steroids_2=[]





    lst_chemical_React= [REACTION_N_dealkylation_1,REACTION_N_dealkylation_2,REACTION_N_dealkylation_3,REACTION_N_dealkylation_4,REACTION_N_dealkylation_5,REACTION_N_dealkylation_6,REACTION_N_dealkylation_7,REACTION_N_dealkylation_8,REACTION_N_dealkylation_9,REACTION_N_dealkylation_10,REACTION_N_dealkylation_11,REACTION_N_dealkylation_12,REACTION_N_dealkylation_13,REACTION_N_dealkylation_14,REACTION_N_dealkylation_15,REACTION_N_dealkylation_16,REACTION_N_dealkylation_17,REACTION_N_dealkylation_18,REACTION_N_dealkylation_19,REACTION_N_dealkylation_20,REACTION_N_dealkylation_21,REACTION_O_demethylation_1,REACTION_O_demethylation_2,REACTION_O_demethylation_3,REACTION_O_demethylation_4,REACTION_O_demethylation_5,REACTION_O_demethylation_6,REACTION_O_demethylation_7,REACTION_O_demethylation_8,REACTION_S_dealkylation_1,REACTION_ aromatic hydroxylation_1,REACTION_ aromatic hydroxylation_2,REACTION_ aromatic hydroxylation_3,REACTION_ aromatic hydroxylation_4,REACTION_ aromatic hydroxylation_5,REACTION_ aromatic hydroxylation_6,REACTION_ aromatic hydroxylation_7,REACTION_ aromatic hydroxylation_8,REACTION_ aromatic hydroxylation_9,REACTION_ aromatic hydroxylation_10,REACTION_ aromatic hydroxylation_11,REACTION_carboxylation_1,REACTION_carboxylation_2,REACTION_carboxylation_3,REACTION_carboxylation_4,REACTION_carboxylation_5,REACTION_aliphatic_hydroxylation_1,REACTION_aliphatic_hydroxylation_2,REACTION_aliphatic_hydroxylation_3,REACTION_aliphatic_hydroxylation_4,REACTION_aliphatic_hydroxylation_5,REACTION_aliphatic_hydroxylation_6,REACTION_aliphatic_hydroxylation_7,REACTION_aliphatic_hydroxylation_8,REACTION_aliphatic_hydroxylation_9,REACTION_aliphatic_hydroxylation_10,REACTION_aliphatic_hydroxylation_11,REACTION_aliphatic_hydroxylation_12,REACTION_aliphatic_hydroxylation_13,REACTION_aliphatic_hydroxylation_14,REACTION_benzylic_hydroxylation_1,REACTION_benzylic_hydroxylation_2,REACTION_benzylic_hydroxylation_3,REACTION_benzylic_hydroxylation_4,REACTION_benzylic_hydroxylation_5,REACTION_benzylic_hydroxylation_6,REACTION_reduction_1,REACTION_reduction_2,REACTION_reduction_3,REACTION_reduction_4,REACTION_reduction_5,REACTION_reduction_6,REACTION_reduction_7,REACTION_reduction_8,REACTION_reduction_9,REACTION_aldehyde_oxidation_1,REACTION_aldehyde_oxidation_2,REACTION_O_deacetylation_1,REACTION_N_deacetylation_1,REACTION_decarboxylation_1,REACTION_decarboxylation_2,REACTION_decarboxylation_3,REACTION_dehydrogenation_1,REACTION_dehydrogenation_2,REACTION_dehydrogenation_3,REACTION_dehydrogenation_4,REACTION_dehydrogenation_5,REACTION_dehydrogenation_6,REACTION_dehydrogenation_7,REACTION_dehydration_1,REACTION_dehydration_2,REACTION_dehydration_3,REACTION_primary_alcohol_oxidatyion_to_carboxyl_1,REACTION_primary_alcohol_oxidatyion_to_carboxyl_2,REACTION_secondary_alcohol_oxidation_to_carbonyl_1,REACTION_secondary_alcohol_oxidation_to_carbonyl_2,REACTION_S_oxidation_1,REACTION_S_oxidation_2,REACTION_S_oxidation_3,REACTION_S_oxidation_4,REACTION_S_oxidation_5,REACTION_S_oxidation_6,REACTION_S_oxidation_7,REACTION_S_oxidation_8,REACTION_S_oxidation_9,REACTION_epoxide_hydrolysis_1,REACTION_epoxide_hydrolysis_2,REACTION_oxidative_deamination_1,REACTION_oxidative_deamination_2,REACTION_oxidative_deamination_3,REACTION_oxidative_deamination_4,REACTION_nitro_1,REACTION_nitro_2,REACTION_nitro_3,REACTION_dehalogenation_1,REACTION_dehalogenation_2,REACTION_dehalogenation_3,REACTION_dehalogenation_4,REACTION_condensation_1a,REACTION_condensation_1b,REACTION_condensation_1c,REACTION_condensation_2a,REACTION_condensation_2b,REACTION_condensation_2c,REACTION_condensation_3a,REACTION_condensation_3b,REACTION_condensation_3c,REACTION_condensation_3d,REACTION_condensation_5a,REACTION_condensation_5b,REACTION_condensation_5c,REACTION_condensation_5d,REACTION_condensation_6a,REACTION_condensation_6b,REACTION_condensation_6c,REACTION_condensation_6d,REACTION_hydrolysis_1,REACTION_hydrolysis_2,REACTION_hydrolysis_3,REACTION_hydrolysis_4,REACTION_hydrolysis_5,REACTION_hydrolysis_6,REACTION_hydrolysis_7,REACTION_hydrolysis_8,REACTION_hydrolysis_9,REACTION_hydrolysis_10,REACTION_N_oxidation_1,REACTION_N_oxidation_2,REACTION_N_oxidation_3,REACTION_N_oxidation_4,REACTION_N_oxidation_5,REACTION_acetyl_shift_1,REACTION_tautomerisation_1,REACTION_special_rules_1,REACTION_special_rules_2,REACTION_special_rules_3,REACTION_special_rules_4,REACTION_special_rules_5,REACTION_special_rules_6,REACTION_special_rules_7,REACTION_special_rules_8,REACTION_special_rules_9,REACTION_special_rules_10,REACTION_special_rules_11,REACTION_special_rules_12,REACTION_special_rules_13,REACTION_special_rules_14,REACTION_special_rules_15,REACTION_steroids_1,REACTION_steroids_2] 
    
    if mol != 'none':    
            REACTION_N_dealkylation_1.append(React.REACTION_N_dealkylation_1(mol))
            REACTION_N_dealkylation_2.append(React.REACTION_N_dealkylation_2(mol))
            REACTION_N_dealkylation_3.append(React.REACTION_N_dealkylation_3(mol))
            REACTION_N_dealkylation_4.append(React.REACTION_N_dealkylation_4(mol))
            REACTION_N_dealkylation_5.append(React.REACTION_N_dealkylation_5(mol))
            REACTION_N_dealkylation_6.append(React.REACTION_N_dealkylation_6(mol))
            REACTION_N_dealkylation_7.append(React.REACTION_N_dealkylation_7(mol))
            REACTION_N_dealkylation_8.append(React.REACTION_N_dealkylation_8(mol))
            REACTION_N_dealkylation_9.append(React.REACTION_N_dealkylation_9(mol))
            REACTION_N_dealkylation_10.append(React.REACTION_N_dealkylation_10(mol))
            REACTION_N_dealkylation_11.append(React.REACTION_N_dealkylation_11(mol))
            REACTION_N_dealkylation_12.append(React.REACTION_N_dealkylation_12(mol))
            REACTION_N_dealkylation_13.append(React.REACTION_N_dealkylation_13(mol))
            REACTION_N_dealkylation_14.append(React.REACTION_N_dealkylation_14(mol))
            REACTION_N_dealkylation_15.append(React.REACTION_N_dealkylation_15(mol))
            REACTION_N_dealkylation_16.append(React.REACTION_N_dealkylation_16(mol))
            REACTION_N_dealkylation_17.append(React.REACTION_N_dealkylation_17(mol))
            REACTION_N_dealkylation_18.append(React.REACTION_N_dealkylation_18(mol))
            REACTION_N_dealkylation_19.append(React.REACTION_N_dealkylation_19(mol))
            REACTION_N_dealkylation_20.append(React.REACTION_N_dealkylation_20(mol))
            REACTION_N_dealkylation_21.append(React.REACTION_N_dealkylation_21(mol))
            REACTION_O_demethylation_1.append(React.REACTION_O_demethylation_1(mol))
            REACTION_O_demethylation_2.append(React.REACTION_O_demethylation_2(mol))
            REACTION_O_demethylation_3.append(React.REACTION_O_demethylation_3(mol))
            REACTION_O_demethylation_4.append(React.REACTION_O_demethylation_4(mol))
            REACTION_O_demethylation_5.append(React.REACTION_O_demethylation_5(mol))
            REACTION_O_demethylation_6.append(React.REACTION_O_demethylation_6(mol))
            REACTION_O_demethylation_7.append(React.REACTION_O_demethylation_7(mol))
            REACTION_O_demethylation_8.append(React.REACTION_O_demethylation_8(mol))
            REACTION_S_dealkylation_1.append(React.REACTION_S_dealkylation_1(mol))
            REACTION_ aromatic hydroxylation_1.append(React.REACTION_ aromatic hydroxylation_1(mol))
            REACTION_ aromatic hydroxylation_2.append(React.REACTION_ aromatic hydroxylation_2(mol))
            REACTION_ aromatic hydroxylation_3.append(React.REACTION_ aromatic hydroxylation_3(mol))
            REACTION_ aromatic hydroxylation_4.append(React.REACTION_ aromatic hydroxylation_4(mol))
            REACTION_ aromatic hydroxylation_5.append(React.REACTION_ aromatic hydroxylation_5(mol))
            REACTION_ aromatic hydroxylation_6.append(React.REACTION_ aromatic hydroxylation_6(mol))
            REACTION_ aromatic hydroxylation_7.append(React.REACTION_ aromatic hydroxylation_7(mol))
            REACTION_ aromatic hydroxylation_8.append(React.REACTION_ aromatic hydroxylation_8(mol))
            REACTION_ aromatic hydroxylation_9.append(React.REACTION_ aromatic hydroxylation_9(mol))
            REACTION_ aromatic hydroxylation_10.append(React.REACTION_ aromatic hydroxylation_10(mol))
            REACTION_ aromatic hydroxylation_11.append(React.REACTION_ aromatic hydroxylation_11(mol))
            REACTION_carboxylation_1.append(React.REACTION_carboxylation_1(mol))
            REACTION_carboxylation_2.append(React.REACTION_carboxylation_2(mol))
            REACTION_carboxylation_3.append(React.REACTION_carboxylation_3(mol))
            REACTION_carboxylation_4.append(React.REACTION_carboxylation_4(mol))
            REACTION_carboxylation_5.append(React.REACTION_carboxylation_5(mol))
            REACTION_aliphatic_hydroxylation_1.append(React.REACTION_aliphatic_hydroxylation_1(mol))
            REACTION_aliphatic_hydroxylation_2.append(React.REACTION_aliphatic_hydroxylation_2(mol))
            REACTION_aliphatic_hydroxylation_3.append(React.REACTION_aliphatic_hydroxylation_3(mol))
            REACTION_aliphatic_hydroxylation_4.append(React.REACTION_aliphatic_hydroxylation_4(mol))
            REACTION_aliphatic_hydroxylation_5.append(React.REACTION_aliphatic_hydroxylation_5(mol))
            REACTION_aliphatic_hydroxylation_6.append(React.REACTION_aliphatic_hydroxylation_6(mol))
            REACTION_aliphatic_hydroxylation_7.append(React.REACTION_aliphatic_hydroxylation_7(mol))
            REACTION_aliphatic_hydroxylation_8.append(React.REACTION_aliphatic_hydroxylation_8(mol))
            REACTION_aliphatic_hydroxylation_9.append(React.REACTION_aliphatic_hydroxylation_9(mol))
            REACTION_aliphatic_hydroxylation_10.append(React.REACTION_aliphatic_hydroxylation_10(mol))
            REACTION_aliphatic_hydroxylation_11.append(React.REACTION_aliphatic_hydroxylation_11(mol))
            REACTION_aliphatic_hydroxylation_12.append(React.REACTION_aliphatic_hydroxylation_12(mol))
            REACTION_aliphatic_hydroxylation_13.append(React.REACTION_aliphatic_hydroxylation_13(mol))
            REACTION_aliphatic_hydroxylation_14.append(React.REACTION_aliphatic_hydroxylation_14(mol))
            REACTION_benzylic_hydroxylation_1.append(React.REACTION_benzylic_hydroxylation_1(mol))
            REACTION_benzylic_hydroxylation_2.append(React.REACTION_benzylic_hydroxylation_2(mol))
            REACTION_benzylic_hydroxylation_3.append(React.REACTION_benzylic_hydroxylation_3(mol))
            REACTION_benzylic_hydroxylation_4.append(React.REACTION_benzylic_hydroxylation_4(mol))
            REACTION_benzylic_hydroxylation_5.append(React.REACTION_benzylic_hydroxylation_5(mol))
            REACTION_benzylic_hydroxylation_6.append(React.REACTION_benzylic_hydroxylation_6(mol))
            REACTION_reduction_1.append(React.REACTION_reduction_1(mol))
            REACTION_reduction_2.append(React.REACTION_reduction_2(mol))
            REACTION_reduction_3.append(React.REACTION_reduction_3(mol))
            REACTION_reduction_4.append(React.REACTION_reduction_4(mol))
            REACTION_reduction_5.append(React.REACTION_reduction_5(mol))
            REACTION_reduction_6.append(React.REACTION_reduction_6(mol))
            REACTION_reduction_7.append(React.REACTION_reduction_7(mol))
            REACTION_reduction_8.append(React.REACTION_reduction_8(mol))
            REACTION_reduction_9.append(React.REACTION_reduction_9(mol))
            REACTION_aldehyde_oxidation_1.append(React.REACTION_aldehyde_oxidation_1(mol))
            REACTION_aldehyde_oxidation_2.append(React.REACTION_aldehyde_oxidation_2(mol))
            REACTION_O_deacetylation_1.append(React.REACTION_O_deacetylation_1(mol))
            REACTION_N_deacetylation_1.append(React.REACTION_N_deacetylation_1(mol))
            REACTION_decarboxylation_1.append(React.REACTION_decarboxylation_1(mol))
            REACTION_decarboxylation_2.append(React.REACTION_decarboxylation_2(mol))
            REACTION_decarboxylation_3.append(React.REACTION_decarboxylation_3(mol))
            REACTION_dehydrogenation_1.append(React.REACTION_dehydrogenation_1(mol))
            REACTION_dehydrogenation_2.append(React.REACTION_dehydrogenation_2(mol))
            REACTION_dehydrogenation_3.append(React.REACTION_dehydrogenation_3(mol))
            REACTION_dehydrogenation_4.append(React.REACTION_dehydrogenation_4(mol))
            REACTION_dehydrogenation_5.append(React.REACTION_dehydrogenation_5(mol))
            REACTION_dehydrogenation_6.append(React.REACTION_dehydrogenation_6(mol))
            REACTION_dehydrogenation_7.append(React.REACTION_dehydrogenation_7(mol))
            REACTION_dehydration_1.append(React.REACTION_dehydration_1(mol))
            REACTION_dehydration_2.append(React.REACTION_dehydration_2(mol))
            REACTION_dehydration_3.append(React.REACTION_dehydration_3(mol))
            REACTION_primary_alcohol_oxidatyion_to_carboxyl_1.append(React.REACTION_primary_alcohol_oxidatyion_to_carboxyl_1(mol))
            REACTION_primary_alcohol_oxidatyion_to_carboxyl_2.append(React.REACTION_primary_alcohol_oxidatyion_to_carboxyl_2(mol))
            REACTION_secondary_alcohol_oxidation_to_carbonyl_1.append(React.REACTION_secondary_alcohol_oxidation_to_carbonyl_1(mol))
            REACTION_secondary_alcohol_oxidation_to_carbonyl_2.append(React.REACTION_secondary_alcohol_oxidation_to_carbonyl_2(mol))
            REACTION_S_oxidation_1.append(React.REACTION_S_oxidation_1(mol))
            REACTION_S_oxidation_2.append(React.REACTION_S_oxidation_2(mol))
            REACTION_S_oxidation_3.append(React.REACTION_S_oxidation_3(mol))
            REACTION_S_oxidation_4.append(React.REACTION_S_oxidation_4(mol))
            REACTION_S_oxidation_5.append(React.REACTION_S_oxidation_5(mol))
            REACTION_S_oxidation_6.append(React.REACTION_S_oxidation_6(mol))
            REACTION_S_oxidation_7.append(React.REACTION_S_oxidation_7(mol))
            REACTION_S_oxidation_8.append(React.REACTION_S_oxidation_8(mol))
            REACTION_S_oxidation_9.append(React.REACTION_S_oxidation_9(mol))
            REACTION_epoxide_hydrolysis_1.append(React.REACTION_epoxide_hydrolysis_1(mol))
            REACTION_epoxide_hydrolysis_2.append(React.REACTION_epoxide_hydrolysis_2(mol))
            REACTION_oxidative_deamination_1.append(React.REACTION_oxidative_deamination_1(mol))
            REACTION_oxidative_deamination_2.append(React.REACTION_oxidative_deamination_2(mol))
            REACTION_oxidative_deamination_3.append(React.REACTION_oxidative_deamination_3(mol))
            REACTION_oxidative_deamination_4.append(React.REACTION_oxidative_deamination_4(mol))
            REACTION_nitro_1.append(React.REACTION_nitro_1(mol))
            REACTION_nitro_2.append(React.REACTION_nitro_2(mol))
            REACTION_nitro_3.append(React.REACTION_nitro_3(mol))
            REACTION_dehalogenation_1.append(React.REACTION_dehalogenation_1(mol))
            REACTION_dehalogenation_2.append(React.REACTION_dehalogenation_2(mol))
            REACTION_dehalogenation_3.append(React.REACTION_dehalogenation_3(mol))
            REACTION_dehalogenation_4.append(React.REACTION_dehalogenation_4(mol))
            REACTION_condensation_1a.append(React.REACTION_condensation_1a(mol))
            REACTION_condensation_1b.append(React.REACTION_condensation_1b(mol))
            REACTION_condensation_1c.append(React.REACTION_condensation_1c(mol))
            REACTION_condensation_2a.append(React.REACTION_condensation_2a(mol))
            REACTION_condensation_2b.append(React.REACTION_condensation_2b(mol))
            REACTION_condensation_2c.append(React.REACTION_condensation_2c(mol))
            REACTION_condensation_3a.append(React.REACTION_condensation_3a(mol))
            REACTION_condensation_3b.append(React.REACTION_condensation_3b(mol))
            REACTION_condensation_3c.append(React.REACTION_condensation_3c(mol))
            REACTION_condensation_3d.append(React.REACTION_condensation_3d(mol))
            REACTION_condensation_5a.append(React.REACTION_condensation_5a(mol))
            REACTION_condensation_5b.append(React.REACTION_condensation_5b(mol))
            REACTION_condensation_5c.append(React.REACTION_condensation_5c(mol))
            REACTION_condensation_5d.append(React.REACTION_condensation_5d(mol))
            REACTION_condensation_6a.append(React.REACTION_condensation_6a(mol))
            REACTION_condensation_6b.append(React.REACTION_condensation_6b(mol))
            REACTION_condensation_6c.append(React.REACTION_condensation_6c(mol))
            REACTION_condensation_6d.append(React.REACTION_condensation_6d(mol))
            REACTION_hydrolysis_1.append(React.REACTION_hydrolysis_1(mol))
            REACTION_hydrolysis_2.append(React.REACTION_hydrolysis_2(mol))
            REACTION_hydrolysis_3.append(React.REACTION_hydrolysis_3(mol))
            REACTION_hydrolysis_4.append(React.REACTION_hydrolysis_4(mol))
            REACTION_hydrolysis_5.append(React.REACTION_hydrolysis_5(mol))
            REACTION_hydrolysis_6.append(React.REACTION_hydrolysis_6(mol))
            REACTION_hydrolysis_7.append(React.REACTION_hydrolysis_7(mol))
            REACTION_hydrolysis_8.append(React.REACTION_hydrolysis_8(mol))
            REACTION_hydrolysis_9.append(React.REACTION_hydrolysis_9(mol))
            REACTION_hydrolysis_10.append(React.REACTION_hydrolysis_10(mol))
            REACTION_N_oxidation_1.append(React.REACTION_N_oxidation_1(mol))
            REACTION_N_oxidation_2.append(React.REACTION_N_oxidation_2(mol))
            REACTION_N_oxidation_3.append(React.REACTION_N_oxidation_3(mol))
            REACTION_N_oxidation_4.append(React.REACTION_N_oxidation_4(mol))
            REACTION_N_oxidation_5.append(React.REACTION_N_oxidation_5(mol))
            REACTION_acetyl_shift_1.append(React.REACTION_acetyl_shift_1(mol))
            REACTION_tautomerisation_1.append(React.REACTION_tautomerisation_1(mol))
            REACTION_special_rules_1.append(React.REACTION_special_rules_1(mol))
            REACTION_special_rules_2.append(React.REACTION_special_rules_2(mol))
            REACTION_special_rules_3.append(React.REACTION_special_rules_3(mol))
            REACTION_special_rules_4.append(React.REACTION_special_rules_4(mol))
            REACTION_special_rules_5.append(React.REACTION_special_rules_5(mol))
            REACTION_special_rules_6.append(React.REACTION_special_rules_6(mol))
            REACTION_special_rules_7.append(React.REACTION_special_rules_7(mol))
            REACTION_special_rules_8.append(React.REACTION_special_rules_8(mol))
            REACTION_special_rules_9.append(React.REACTION_special_rules_9(mol))
            REACTION_special_rules_10.append(React.REACTION_special_rules_10(mol))
            REACTION_special_rules_11.append(React.REACTION_special_rules_11(mol))
            REACTION_special_rules_12.append(React.REACTION_special_rules_12(mol))
            REACTION_special_rules_13.append(React.REACTION_special_rules_13(mol))
            REACTION_special_rules_14.append(React.REACTION_special_rules_14(mol))
            REACTION_special_rules_15.append(React.REACTION_special_rules_15(mol))
            REACTION_steroids_1.append(React.REACTION_steroids_1(mol))
            REACTION_steroids_2.append(React.REACTION_steroids_2(mol))

    else:
        for chem_group in lst_chemical_React:
            chem_group.append('none')
       
    out = pd.DataFrame(list(zip(REACTION_N_dealkylation_1,REACTION_N_dealkylation_2,REACTION_N_dealkylation_3,REACTION_N_dealkylation_4,REACTION_N_dealkylation_5,REACTION_N_dealkylation_6,REACTION_N_dealkylation_7,REACTION_N_dealkylation_8,REACTION_N_dealkylation_9,REACTION_N_dealkylation_10,REACTION_N_dealkylation_11,REACTION_N_dealkylation_12,REACTION_N_dealkylation_13,REACTION_N_dealkylation_14,REACTION_N_dealkylation_15,REACTION_N_dealkylation_16,REACTION_N_dealkylation_17,REACTION_N_dealkylation_18,REACTION_N_dealkylation_19,REACTION_N_dealkylation_20,REACTION_N_dealkylation_21,REACTION_O_demethylation_1,REACTION_O_demethylation_2,REACTION_O_demethylation_3,REACTION_O_demethylation_4,REACTION_O_demethylation_5,REACTION_O_demethylation_6,REACTION_O_demethylation_7,REACTION_O_demethylation_8,REACTION_S_dealkylation_1,REACTION_ aromatic hydroxylation_1,REACTION_ aromatic hydroxylation_2,REACTION_ aromatic hydroxylation_3,REACTION_ aromatic hydroxylation_4,REACTION_ aromatic hydroxylation_5,REACTION_ aromatic hydroxylation_6,REACTION_ aromatic hydroxylation_7,REACTION_ aromatic hydroxylation_8,REACTION_ aromatic hydroxylation_9,REACTION_ aromatic hydroxylation_10,REACTION_ aromatic hydroxylation_11,REACTION_carboxylation_1,REACTION_carboxylation_2,REACTION_carboxylation_3,REACTION_carboxylation_4,REACTION_carboxylation_5,REACTION_aliphatic_hydroxylation_1,REACTION_aliphatic_hydroxylation_2,REACTION_aliphatic_hydroxylation_3,REACTION_aliphatic_hydroxylation_4,REACTION_aliphatic_hydroxylation_5,REACTION_aliphatic_hydroxylation_6,REACTION_aliphatic_hydroxylation_7,REACTION_aliphatic_hydroxylation_8,REACTION_aliphatic_hydroxylation_9,REACTION_aliphatic_hydroxylation_10,REACTION_aliphatic_hydroxylation_11,REACTION_aliphatic_hydroxylation_12,REACTION_aliphatic_hydroxylation_13,REACTION_aliphatic_hydroxylation_14,REACTION_benzylic_hydroxylation_1,REACTION_benzylic_hydroxylation_2,REACTION_benzylic_hydroxylation_3,REACTION_benzylic_hydroxylation_4,REACTION_benzylic_hydroxylation_5,REACTION_benzylic_hydroxylation_6,REACTION_reduction_1,REACTION_reduction_2,REACTION_reduction_3,REACTION_reduction_4,REACTION_reduction_5,REACTION_reduction_6,REACTION_reduction_7,REACTION_reduction_8,REACTION_reduction_9,REACTION_aldehyde_oxidation_1,REACTION_aldehyde_oxidation_2,REACTION_O_deacetylation_1,REACTION_N_deacetylation_1,REACTION_decarboxylation_1,REACTION_decarboxylation_2,REACTION_decarboxylation_3,REACTION_dehydrogenation_1,REACTION_dehydrogenation_2,REACTION_dehydrogenation_3,REACTION_dehydrogenation_4,REACTION_dehydrogenation_5,REACTION_dehydrogenation_6,REACTION_dehydrogenation_7,REACTION_dehydration_1,REACTION_dehydration_2,REACTION_dehydration_3,REACTION_primary_alcohol_oxidatyion_to_carboxyl_1,REACTION_primary_alcohol_oxidatyion_to_carboxyl_2,REACTION_secondary_alcohol_oxidation_to_carbonyl_1,REACTION_secondary_alcohol_oxidation_to_carbonyl_2,REACTION_S_oxidation_1,REACTION_S_oxidation_2,REACTION_S_oxidation_3,REACTION_S_oxidation_4,REACTION_S_oxidation_5,REACTION_S_oxidation_6,REACTION_S_oxidation_7,REACTION_S_oxidation_8,REACTION_S_oxidation_9,REACTION_epoxide_hydrolysis_1,REACTION_epoxide_hydrolysis_2,REACTION_oxidative_deamination_1,REACTION_oxidative_deamination_2,REACTION_oxidative_deamination_3,REACTION_oxidative_deamination_4,REACTION_nitro_1,REACTION_nitro_2,REACTION_nitro_3,REACTION_dehalogenation_1,REACTION_dehalogenation_2,REACTION_dehalogenation_3,REACTION_dehalogenation_4,REACTION_condensation_1a,REACTION_condensation_1b,REACTION_condensation_1c,REACTION_condensation_2a,REACTION_condensation_2b,REACTION_condensation_2c,REACTION_condensation_3a,REACTION_condensation_3b,REACTION_condensation_3c,REACTION_condensation_3d,REACTION_condensation_5a,REACTION_condensation_5b,REACTION_condensation_5c,REACTION_condensation_5d,REACTION_condensation_6a,REACTION_condensation_6b,REACTION_condensation_6c,REACTION_condensation_6d,REACTION_hydrolysis_1,REACTION_hydrolysis_2,REACTION_hydrolysis_3,REACTION_hydrolysis_4,REACTION_hydrolysis_5,REACTION_hydrolysis_6,REACTION_hydrolysis_7,REACTION_hydrolysis_8,REACTION_hydrolysis_9,REACTION_hydrolysis_10,REACTION_N_oxidation_1,REACTION_N_oxidation_2,REACTION_N_oxidation_3,REACTION_N_oxidation_4,REACTION_N_oxidation_5,REACTION_acetyl_shift_1,REACTION_tautomerisation_1,REACTION_special_rules_1,REACTION_special_rules_2,REACTION_special_rules_3,REACTION_special_rules_4,REACTION_special_rules_5,REACTION_special_rules_6,REACTION_special_rules_7,REACTION_special_rules_8,REACTION_special_rules_9,REACTION_special_rules_10,REACTION_special_rules_11,REACTION_special_rules_12,REACTION_special_rules_13,REACTION_special_rules_14,REACTION_special_rules_15,REACTION_steroids_1,REACTION_steroids_2)),
    columns=['REACTION_N_dealkylation_1','REACTION_N_dealkylation_2','REACTION_N_dealkylation_3','REACTION_N_dealkylation_4','REACTION_N_dealkylation_5','REACTION_N_dealkylation_6','REACTION_N_dealkylation_7','REACTION_N_dealkylation_8','REACTION_N_dealkylation_9','REACTION_N_dealkylation_10','REACTION_N_dealkylation_11','REACTION_N_dealkylation_12','REACTION_N_dealkylation_13','REACTION_N_dealkylation_14','REACTION_N_dealkylation_15','REACTION_N_dealkylation_16','REACTION_N_dealkylation_17','REACTION_N_dealkylation_18','REACTION_N_dealkylation_19','REACTION_N_dealkylation_20','REACTION_N_dealkylation_21','REACTION_O_demethylation_1','REACTION_O_demethylation_2','REACTION_O_demethylation_3','REACTION_O_demethylation_4','REACTION_O_demethylation_5','REACTION_O_demethylation_6','REACTION_O_demethylation_7','REACTION_O_demethylation_8','REACTION_S_dealkylation_1','REACTION_ aromatic hydroxylation_1','REACTION_ aromatic hydroxylation_2','REACTION_ aromatic hydroxylation_3','REACTION_ aromatic hydroxylation_4','REACTION_ aromatic hydroxylation_5','REACTION_ aromatic hydroxylation_6','REACTION_ aromatic hydroxylation_7','REACTION_ aromatic hydroxylation_8','REACTION_ aromatic hydroxylation_9','REACTION_ aromatic hydroxylation_10','REACTION_ aromatic hydroxylation_11','REACTION_carboxylation_1','REACTION_carboxylation_2','REACTION_carboxylation_3','REACTION_carboxylation_4','REACTION_carboxylation_5','REACTION_aliphatic_hydroxylation_1','REACTION_aliphatic_hydroxylation_2','REACTION_aliphatic_hydroxylation_3','REACTION_aliphatic_hydroxylation_4','REACTION_aliphatic_hydroxylation_5','REACTION_aliphatic_hydroxylation_6','REACTION_aliphatic_hydroxylation_7','REACTION_aliphatic_hydroxylation_8','REACTION_aliphatic_hydroxylation_9','REACTION_aliphatic_hydroxylation_10','REACTION_aliphatic_hydroxylation_11','REACTION_aliphatic_hydroxylation_12','REACTION_aliphatic_hydroxylation_13','REACTION_aliphatic_hydroxylation_14','REACTION_benzylic_hydroxylation_1','REACTION_benzylic_hydroxylation_2','REACTION_benzylic_hydroxylation_3','REACTION_benzylic_hydroxylation_4','REACTION_benzylic_hydroxylation_5','REACTION_benzylic_hydroxylation_6','REACTION_reduction_1','REACTION_reduction_2','REACTION_reduction_3','REACTION_reduction_4','REACTION_reduction_5','REACTION_reduction_6','REACTION_reduction_7','REACTION_reduction_8','REACTION_reduction_9','REACTION_aldehyde_oxidation_1','REACTION_aldehyde_oxidation_2','REACTION_O_deacetylation_1','REACTION_N_deacetylation_1','REACTION_decarboxylation_1','REACTION_decarboxylation_2','REACTION_decarboxylation_3','REACTION_dehydrogenation_1','REACTION_dehydrogenation_2','REACTION_dehydrogenation_3','REACTION_dehydrogenation_4','REACTION_dehydrogenation_5','REACTION_dehydrogenation_6','REACTION_dehydrogenation_7','REACTION_dehydration_1','REACTION_dehydration_2','REACTION_dehydration_3','REACTION_primary_alcohol_oxidatyion_to_carboxyl_1','REACTION_primary_alcohol_oxidatyion_to_carboxyl_2','REACTION_secondary_alcohol_oxidation_to_carbonyl_1','REACTION_secondary_alcohol_oxidation_to_carbonyl_2','REACTION_S_oxidation_1','REACTION_S_oxidation_2','REACTION_S_oxidation_3','REACTION_S_oxidation_4','REACTION_S_oxidation_5','REACTION_S_oxidation_6','REACTION_S_oxidation_7','REACTION_S_oxidation_8','REACTION_S_oxidation_9','REACTION_epoxide_hydrolysis_1','REACTION_epoxide_hydrolysis_2','REACTION_oxidative_deamination_1','REACTION_oxidative_deamination_2','REACTION_oxidative_deamination_3','REACTION_oxidative_deamination_4','REACTION_nitro_1','REACTION_nitro_2','REACTION_nitro_3','REACTION_dehalogenation_1','REACTION_dehalogenation_2','REACTION_dehalogenation_3','REACTION_dehalogenation_4','REACTION_condensation_1a','REACTION_condensation_1b','REACTION_condensation_1c','REACTION_condensation_2a','REACTION_condensation_2b','REACTION_condensation_2c','REACTION_condensation_3a','REACTION_condensation_3b','REACTION_condensation_3c','REACTION_condensation_3d','REACTION_condensation_5a','REACTION_condensation_5b','REACTION_condensation_5c','REACTION_condensation_5d','REACTION_condensation_6a','REACTION_condensation_6b','REACTION_condensation_6c','REACTION_condensation_6d','REACTION_hydrolysis_1','REACTION_hydrolysis_2','REACTION_hydrolysis_3','REACTION_hydrolysis_4','REACTION_hydrolysis_5','REACTION_hydrolysis_6','REACTION_hydrolysis_7','REACTION_hydrolysis_8','REACTION_hydrolysis_9','REACTION_hydrolysis_10','REACTION_N_oxidation_1','REACTION_N_oxidation_2','REACTION_N_oxidation_3','REACTION_N_oxidation_4','REACTION_N_oxidation_5','REACTION_acetyl_shift_1','REACTION_tautomerisation_1','REACTION_special_rules_1','REACTION_special_rules_2','REACTION_special_rules_3','REACTION_special_rules_4','REACTION_special_rules_5','REACTION_special_rules_6','REACTION_special_rules_7','REACTION_special_rules_8','REACTION_special_rules_9','REACTION_special_rules_10','REACTION_special_rules_11','REACTION_special_rules_12','REACTION_special_rules_13','REACTION_special_rules_14','REACTION_special_rules_15','REACTION_steroids_1','REACTION_steroids_2'])
    return out
